// Code generated by "packer-sdc mapstructure-to-hcl2"; DO NOT EDIT.

package common

import (
	"github.com/hashicorp/hcl/v2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

// FlatGalaxyConfig is an auto-generated flat version of GalaxyConfig.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatGalaxyConfig struct {
	GalaxyFile            *string `mapstructure:"galaxy_file" cty:"galaxy_file" hcl:"galaxy_file"`
	GalaxyCommand         *string `mapstructure:"galaxy_command" cty:"galaxy_command" hcl:"galaxy_command"`
	GalaxyForceInstall    *bool   `mapstructure:"galaxy_force_install" cty:"galaxy_force_install" hcl:"galaxy_force_install"`
	GalaxyRolesPath       *string `mapstructure:"galaxy_roles_path" cty:"galaxy_roles_path" hcl:"galaxy_roles_path"`
	GalaxyCollectionsPath *string `mapstructure:"galaxy_collections_path" cty:"galaxy_collections_path" hcl:"galaxy_collections_path"`
	GalaxyForceWithDeps   *bool   `mapstructure:"galaxy_force_with_deps" cty:"galaxy_force_with_deps" hcl:"galaxy_force_with_deps"`
}

// FlatMapstructure returns a new FlatGalaxyConfig.
// FlatGalaxyConfig is an auto-generated flat version of GalaxyConfig.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*GalaxyConfig) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatGalaxyConfig)
}

// HCL2Spec returns the hcl spec of a GalaxyConfig.
// This spec is used by HCL to read the fields of GalaxyConfig.
// The decoded values from this spec will then be applied to a FlatGalaxyConfig.
func (*FlatGalaxyConfig) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"galaxy_file":             &hcldec.AttrSpec{Name: "galaxy_file", Type: cty.String, Required: false},
		"galaxy_command":          &hcldec.AttrSpec{Name: "galaxy_command", Type: cty.String, Required: false},
		"galaxy_force_install":    &hcldec.AttrSpec{Name: "galaxy_force_install", Type: cty.Bool, Required: false},
		"galaxy_roles_path":       &hcldec.AttrSpec{Name: "galaxy_roles_path", Type: cty.String, Required: false},
		"galaxy_collections_path": &hcldec.AttrSpec{Name: "galaxy_collections_path", Type: cty.String, Required: false},
		"galaxy_force_with_deps":  &hcldec.AttrSpec{Name: "galaxy_force_with_deps", Type: cty.Bool, Required: false},
	}
	return s
}
