# Copyright IBM Corp. 2013, 2025
# SPDX-License-Identifier: MPL-2.0

packer {
  required_version = ">1.7.0"

  required_plugins {
    docker = {
      source = "github.com/hashicorp/docker"
      version = ">=0.0.7"
    }
  }
}

source "docker" "autogenerated_1" {
  discard = true
  image   = "williamyeh/ansible:centos7"
}

build {
  sources = ["source.docker.autogenerated_1"]

  provisioner "ansible" {
    playbook_file = "test-fixtures/long-debug-message.yml"
  }
}
